# try:
#     a = int(input("Enter a: "))
#     b = int(input("Enter b: "))
#     print(f"Answer = {a/b}")
# except:
#     print("Cannot divide a number by zero")


# try:
#     num = int(input("Enter a number: "))
#     print(num)
# except:
#     print("Please enter an integer")

# li = ['a', 'b', 'c', 'd', 'e']
# try:
#     a = int(input("Enter the index position: "))
#     print(li[a])
# except:
#     print("Enter a valid index position")


# try:
#     a = int(input("Enter a: "))
#     b = int(input("Enter b: "))
#     print(f"Answer = {a/b}")
# except ZeroDivisionError:
#     print("Cannot divide a number by zero")
# except ValueError:
#     print("Please enter an integer")

 # Create a quadratic equation solver using exception handling
# try:
#     a = int(input("Enter a: "))
#     b = int(input("Enter b: "))
#     c = int(input("Enter c: "))
#     d = (b**2) - (4*a*c)
#     x1 = (-b + (d**0.5)) / (2*a)
#     x2 = (-b - (d**0.5)) / (2*a)
#     print(f"The solutions are: x1 = {x1}, x2 = {x2}")
# except ZeroDivisionError:
#     print("Cannot divide a number by zero")
# except ValueError as manu:
#     print(manu)


# try:
#     a = int(input("Enter a: "))
#     b = int(input("Enter b: "))
#     print(f"Answer = {a/b}")
# except Exception as e:
#     print(e)

# What is a assertion in exception handing ?
# sample program
